# ===== basic config ===== 
partition: dir  # partition method, including ['iid', 'dir', 'pat', 'group']
train_ratio: 0.75  # train data ratio
batch_size: 10  # batch size

client_num: 16  # number of clients
dir_path: cifar100  # dataset path

# ===== Dirichlet =====
alpha: 1.0  # Dirichlet distribution parameter, used in 'dir' partition method

# ===== Pathological =====
class_per_client: 2  # number of classes per client, used in 'pat' partition method

# ===== Group =====
group_num: 10  # number of groups, used in 'group' partition method
iid_proportion: 0.2  # proportion of IID data in each group, used in 'group' partition method
